# This is a basic workflow to help you get started with Actions

name: Test Experimental Features

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  experimental:

    strategy:
      fail-fast: false
      matrix:
        # note: in the 2nd half of 2022 the setup-mingw was often failing on
        # windows-latest. revisit someday (perhaps when there's an @v3)
        #os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        os: ['ubuntu-latest', 'windows-2019', 'macos-latest']

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4.1.6

      # experiment: maybe don't need this?
      # update: looks like we do: with this commented out, the build hung
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2.2.0
        if: matrix.os == 'windows-2019'
        with:
          platform: x64
          static: 0

      - name: Set up Python 3.11 ${{ matrix.os }}
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.11'

      - name: Install dependencies including ninja ${{ matrix.os }}
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install ninja psutil
          # sudo apt-get update

      - name: Test experimental packages ${{ matrix.os }}
        run: |
          python runtest.py test/import.py test/ninja
